apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-fbc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-fbc
    app.kubernetes.io/part-of: fbc-e2e-test
  name: simple-fbc
  namespace: dev-release-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: simple-fbc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: simple-fbc
    spec:
      containers:
      - image: quay.io/scoheb/user-workload:dev-release-team-simple-fbc
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
