apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 413-fbc-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 413-fbc-test
    app.kubernetes.io/part-of: fbc-e2e-test
  name: 413-fbc-test
  namespace: dev-release-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: 413-fbc-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: 413-fbc-test
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:71c42c96f41ea2480d619826b52f9f7d2f7e2a4b9b316df5928e06ae6c115aa1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
